# Generated by Django 3.1 on 2020-09-28 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sisnlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Destinatario_Nome :')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Destinatario_CNPJ :')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Destinatario_CPF :')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Destinatario_Data_cadastro :')),
                ('endereco', models.CharField(blank=True, max_length=250, null=True, verbose_name='Destinatario_Endereço :')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Destinatario_Telefone :')),
                ('cel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Destinatario_celular :')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destinatario_Email :')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Destinatario Observação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Destinatario_Usuario :')),
            ],
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fornecedor_celular :'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Fornecedor_CNPJ :'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Fornecedor_CPF :'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fornecedor_Data_cadastro :'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Fornecedor_Email :'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fornecedor_Endereço :'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fornecedor_Telefone :'),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota fiscal')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_de Cadastro Destinatario')),
                ('nf_foto', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto_NFo')),
                ('obs', models.TextField(blank=True, verbose_name='Diverso_Observação :')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Destinatario_Saida', to='sisnlab.destinatario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioSaida :')),
            ],
        ),
        migrations.CreateModel(
            name='ItensSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_id', models.IntegerField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Quantidade_Saida :')),
                ('reagente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reagente_Saida', to='sisnlab.reagente')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Unidade_Saida', to='sisnlab.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario_Saida :')),
            ],
        ),
    ]
